package Ismael;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henrygbc
 */
public class Platos extends javax.swing.JFrame {
    DefaultTableModel modelo;
    String ID_Editar = "";
    String Ruta = "C:/Users/Carolina/Ismaels/";
    /**
     * Creates new form Platos
     */
    public Platos() {
        initComponents();
        setLocation(380,250);
        jbtnMod.setVisible(false);
        jbtnCancelar.setVisible(false);
        
         modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        this.jTable1.setModel(modelo);
        llenarPlatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    public void llenarPlatos()
    {
        String []Datos = new String[4];
       Connection c = null;
       Statement stmt = null;
       try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:"+Ruta+"Ismael.sqlite");
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");
            
            stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery( "SELECT * FROM PLATOS;" );
            
         while ( rs.next() ) {
                int id = rs.getInt("ID_P");
                String name = rs.getString("NOMBRE");
                String apellido = rs.getString("DESCRIPCION");
                float precio = rs.getFloat("PRECIO");
                Datos[0] = Integer.toString(id);
                Datos[1] = name;
                Datos[2] = apellido;
                Datos[3] = Float.toString(precio);
                modelo.addRow(Datos);
        }
         rs.close();
        stmt.close();
        c.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }
    public void removerFilasTabla()
   {
      int cantidadFilas = jTable1.getRowCount();
       for (int i = cantidadFilas-1; i >=0; i--) {
            modelo.removeRow(i);
           
       }
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxfNombre = new javax.swing.JTextField();
        jtxfDescripcion = new javax.swing.JTextField();
        jtxfPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnAgregar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnMod = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        label1.setText("Platos");

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel2.setText("Descripción: ");

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel3.setText("Precio");

        jtxfNombre.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jtxfNombre.setToolTipText("");

        jtxfDescripcion.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N

        jtxfPrecio.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtnAgregar.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });

        jbtnEliminar.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jbtnEditar.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        jbtnMod.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jbtnMod.setText("Modificar");
        jbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModActionPerformed(evt);
            }
        });

        jbtnCancelar.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnAtras.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jbtnAtras.setText("Atras");
        jbtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jtxfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtnAtras)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtnMod)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnCancelar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtnAgregar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnEditar)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnMod)
                            .addComponent(jbtnCancelar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jbtnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAgregar)
                    .addComponent(jbtnEliminar)
                    .addComponent(jbtnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
          String []Datos = new String[4];
        Datos[1]= jtxfNombre.getText();
        jtxfNombre.setText(null);
        Datos[2] = jtxfDescripcion.getText();
        jtxfDescripcion.setText(null);
        Datos[3] = jtxfPrecio.getText();
        jtxfPrecio.setText(null);
        
        
        
        //INSERT INTO CLIENTES (NOMBRE,APELLIDO,TELEFONO) VALUES (?1,?2,?3)
        Connection c = null;
        Statement stmt = null;
        
        
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:"+Ruta+"Ismael.sqlite");
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");

             stmt = c.createStatement();
             
             String sql = "INSERT INTO PLATOS (NOMBRE,DESCRIPCION,PRECIO) VALUES (?,?,?)";
             PreparedStatement pst;
             pst = c.prepareStatement(sql);
             
             pst.setString(1, Datos[1]);
             pst.setString(2, Datos[2]);
             pst.setString(3, Datos[3]);
             
             int n = pst.executeUpdate();
             
             ResultSet rs = stmt.executeQuery( "SELECT ID_P FROM PLATOS WHERE NOMBRE "
                     + "='"+Datos[1]+"' AND DESCRIPCION ='"+Datos[2]+"' AND PRECIO ='"+Datos[3]+"' ;" );
                 
             while ( rs.next() ) {
                int id = rs.getInt("ID_P");
                Datos[0] = Integer.toString(id);
             }
             
             stmt.close();
             c.commit();
             c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        //AGREGAR A TABLA JFRAME
        modelo.addRow(Datos);
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        String []Datos = new String[4]; 
        
        int FilaSeleccionada = jTable1.getSelectedRow();
        if(FilaSeleccionada>=0)
        {   
           Datos[0] = modelo.getValueAt(FilaSeleccionada, 0).toString();
            Connection c = null;
            Statement stmt = null;
            try {
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:"+Ruta+"Ismael.sqlite");
              c.setAutoCommit(false);
              System.out.println("Opened database successfully");

              stmt = c.createStatement();
              String sql = "DELETE from PLATOS where ID_P='"+Datos[0]+"';";
              stmt.executeUpdate(sql);
              c.commit();
            
            stmt.close();
            c.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
              
              modelo.removeRow(FilaSeleccionada);
            
        }else{
            JOptionPane.showMessageDialog(null,"Tabla vacia o no seleccionó fila");
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        
        String []Datos = new String[4]; 
        int FilaSeleccionada = jTable1.getSelectedRow();
        if(FilaSeleccionada>=0)
        {
           Datos[0] = modelo.getValueAt(FilaSeleccionada, 0).toString();
           Datos[1] = modelo.getValueAt(FilaSeleccionada, 1).toString();
           Datos[2] = modelo.getValueAt(FilaSeleccionada, 2).toString();
           Datos[3] = modelo.getValueAt(FilaSeleccionada, 3).toString();
           ID_Editar = Datos[0];
           jtxfNombre.setText(Datos[1]);
           jtxfDescripcion.setText(Datos[2]);
           jtxfPrecio.setText(Datos[3]);
        }else{
            JOptionPane.showMessageDialog(null,"Tabla vacia o no seleccionó fila");
        }
        
        jbtnMod.setVisible(true);
        jbtnCancelar.setVisible(true);
        jbtnAgregar.setVisible(false);
        jbtnEliminar.setVisible(false);
        jbtnEditar.setVisible(false);
                       
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModActionPerformed
      String []Datos = new String[4];
        Datos[1]= jtxfNombre.getText();
        jtxfNombre.setText(null);
        Datos[2] = jtxfDescripcion.getText();
        jtxfDescripcion.setText(null);
        Datos[3] = jtxfPrecio.getText();
        jtxfPrecio.setText(null);
        Connection c = null;
        Statement stmt = null;
        try{ 
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:"+Ruta+"Ismael.sqlite");
            c.setAutoCommit(false);
            stmt = c.createStatement();
            System.out.println("Opened database successfully");
           
            
             int n = stmt.executeUpdate("UPDATE PLATOS SET "
                     + "NOMBRE ='"+Datos[1]+"', DESCRIPCION ='"+Datos[2]+"', PRECIO ='"+Datos[3]+"' WHERE ID_P= '"+ID_Editar+"' ");
              stmt.close();
             c.commit();
             c.close();
             removerFilasTabla();
             llenarPlatos();
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
          jbtnMod.setVisible(false);
        jbtnCancelar.setVisible(false);
        jbtnAgregar.setVisible(true);
        jbtnEliminar.setVisible(true);
        jbtnEditar.setVisible(true);
        jtxfNombre.setText(null);
        jtxfDescripcion.setText(null);
        jtxfPrecio.setText(null);
    }//GEN-LAST:event_jbtnModActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        jbtnMod.setVisible(false);
        jbtnCancelar.setVisible(false);
        jbtnAgregar.setVisible(true);
        jbtnEliminar.setVisible(true);
        jbtnEditar.setVisible(true);
        jtxfNombre.setText(null);
        jtxfDescripcion.setText(null);
        jtxfPrecio.setText(null);
        
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtrasActionPerformed
       Pedidos pedidos = new Pedidos();
       pedidos.setVisible(true);
       dispose();
    }//GEN-LAST:event_jbtnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Platos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnAtras;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnMod;
    private javax.swing.JTextField jtxfDescripcion;
    private javax.swing.JTextField jtxfNombre;
    private javax.swing.JTextField jtxfPrecio;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
